  name: Update osp-app
  hosts: osp-app
  tasks:
# 1 Rocket notification: Starting update

# 2 Check commit: update needed?
# if no:
# 2.1 Rocket notification: Cancel update
# if yes:

# 3 Check available space on disk: does the server have enough space?

# if no:
# 3.1 Rocket notification: Server full
# if yes:

# 4 Ruby version: Is the ruby version up-to-date?
# if no:
# 4.1 Rocket notification: Ruby needs update
# if yes:

# Backup DB in pg_dump folder
  - name: Backup osp-app database in pg_dump folder
    postgresql_db:
      name: osp_app
      state: dump
      target: home/mako/pg_dump/osp_app-$(date +%Y%m%d%H%M%S).sql

# Backup APP in osp_app.bak folder
  - name: Backup osp-app database in pg_dump folder
    copy:
      src: /home/mako/osp-app
      dest: /home/mako/osp-app.bkp

# Git pull
  - name: Git pull last commits
    git:
      repo: git@github.com:OpenSourcePolitics/osp-app.git
      dest: /home/mako/osp-app
      version: 0.21-stable

# bundle installation
  - name: Bundle install
    bundler:
      state: present
      chdir: /home/mako/osp-app
    
# Migration
  - name: Run migrations
    shell:
      cmd: bundle exec rails db:migrate
      chdir: /home/mako/osp-app

# Assets clobber / Assets precompile
  - name: Precompile assets 
    shell:
      cmd: RAILS_ENV=production bundle exec rails tmp:cache:clear assets:clobber assets:precompile
      chdir: /home/mako/osp-app

# Restart nginx + sidekiq
  - name: Restart sidekiq
    service:
      name: sidekiq
      state: restarted

  - name: Restart nginx
    service:
      name: nginx
      state: restarted

# curl homepage
  - name: Check osp-app homepage
    uri:
      url: {{ osp-app-url }}
      
# Rocket notification: End of update

